Review
polinakorotenkova/todolist-api pull request #1
Opened 2022-08-05 13:22 UTC by polinakorotenkova

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        let result = await loginQuery(data.email, data.password)
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        var token = jwt.sign({ userId: result.id,name: data.name }, 'nasrat');
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +var jwt = require('jsonwebtoken');
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        let result = await regisration(data.email, data.password, data.name)
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        console.log(result.rows[0].id)
delete

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        var token = jwt.sign({ userId: result.rows[0].id ,name: data.name, }, 'nasrat');
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        let result = await addTodos(data.text, data.isDone, decoded.userId)
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        let result = await receivingTodos(decoded.userId)
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        let result = await deleteTodos(data.id, userId)
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +        let result = await changeTodo (data.id, userId, data.text, data.isDone)
const

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +  console.log(`Запрошенный адрес: ${request.url}`);
delete

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +  console.log('подключаемся к базе данных')
delete

2022-08-06 14:39 UTC, LevaSokolov commented on api.js
> +  console.log('Сервер начал прослушивание запросов на порту 2000');
delete

2022-08-06 14:39 UTC, LevaSokolov commented on changeTodos.js
> +  let isDoneSql = ''
const

2022-08-07 14:33 UTC, MusicCorner requested changes
Install eslint to you project + install eslint extension if you’re using vscode (use airbnb rules)

Move strings, numbers and all that stuff into constants

Also please move repeatable code into functions

2022-08-07 14:33 UTC, MusicCorner commented on api.js
> +        const data = JSON.parse(body)
move into a separated function

2022-09-20 07:39 UTC, merged